// AUTO-GENERATED by scripts/bundle-migrations.mjs — do not edit by hand.
// Run `node scripts/bundle-migrations.mjs` whenever migrations change.
export type Migration = { name: string; sql: string };
export const MIGRATIONS: Migration[] = [
  { name: "20260621195230_2b87c4d8-afaa-413e-a6e0-b54a34fc46a5.sql", sql: `
-- Enums
CREATE TYPE public.formador_estado AS ENUM ('ativo','inativo','ferias','baixa_medica','suspenso','arquivado');
CREATE TYPE public.curso_tipologia AS ENUM ('EFA','ERFA','MFA','OUTRO');
CREATE TYPE public.curso_estado AS ENUM ('planeado','ativo','concluido','suspenso','cancelado');

-- Trigger function for updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

-- FORMADORES
CREATE TABLE public.formadores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT NOT NULL,
  nif TEXT,
  cc TEXT,
  validade_cc DATE,
  morada TEXT,
  codigo_postal TEXT,
  localidade TEXT,
  telemovel TEXT,
  email TEXT,
  iban TEXT,
  habilitacoes TEXT,
  ccp TEXT,
  validade_ccp DATE,
  observacoes TEXT,
  estado public.formador_estado NOT NULL DEFAULT 'ativo',
  cor TEXT NOT NULL DEFAULT '#E11D48',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formadores TO authenticated;
GRANT ALL ON public.formadores TO service_role;
ALTER TABLE public.formadores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full access formadores" ON public.formadores FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_formadores_upd BEFORE UPDATE ON public.formadores FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- INATIVIDADES
CREATE TABLE public.formador_inatividades (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  formador_id UUID NOT NULL REFERENCES public.formadores(id) ON DELETE CASCADE,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  motivo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formador_inatividades TO authenticated;
GRANT ALL ON public.formador_inatividades TO service_role;
ALTER TABLE public.formador_inatividades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full inatividades" ON public.formador_inatividades FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- DOCUMENTOS
CREATE TABLE public.formador_documentos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  formador_id UUID NOT NULL REFERENCES public.formadores(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL,
  nome TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  validade DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formador_documentos TO authenticated;
GRANT ALL ON public.formador_documentos TO service_role;
ALTER TABLE public.formador_documentos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full documentos" ON public.formador_documentos FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- CURSOS
CREATE TABLE public.cursos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo TEXT NOT NULL,
  nome TEXT NOT NULL,
  tipologia public.curso_tipologia NOT NULL DEFAULT 'EFA',
  data_inicio DATE,
  data_fim DATE,
  estado public.curso_estado NOT NULL DEFAULT 'planeado',
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cursos TO authenticated;
GRANT ALL ON public.cursos TO service_role;
ALTER TABLE public.cursos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full cursos" ON public.cursos FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_cursos_upd BEFORE UPDATE ON public.cursos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- UFCDs (catalogo)
CREATE TABLE public.ufcds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo TEXT NOT NULL UNIQUE,
  designacao TEXT NOT NULL,
  horas_referencia INTEGER NOT NULL DEFAULT 25,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ufcds TO authenticated;
GRANT ALL ON public.ufcds TO service_role;
ALTER TABLE public.ufcds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full ufcds" ON public.ufcds FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- CURSO_UFCDS (UFCD atribuida a curso)
CREATE TABLE public.curso_ufcds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_id UUID NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  ufcd_id UUID NOT NULL REFERENCES public.ufcds(id) ON DELETE RESTRICT,
  horas_totais INTEGER NOT NULL DEFAULT 25,
  ordem INTEGER NOT NULL DEFAULT 0,
  concluida BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (curso_id, ufcd_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.curso_ufcds TO authenticated;
GRANT ALL ON public.curso_ufcds TO service_role;
ALTER TABLE public.curso_ufcds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full curso_ufcds" ON public.curso_ufcds FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- CURSO_UFCD_FORMADORES
CREATE TABLE public.curso_ufcd_formadores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_ufcd_id UUID NOT NULL REFERENCES public.curso_ufcds(id) ON DELETE CASCADE,
  formador_id UUID NOT NULL REFERENCES public.formadores(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (curso_ufcd_id, formador_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.curso_ufcd_formadores TO authenticated;
GRANT ALL ON public.curso_ufcd_formadores TO service_role;
ALTER TABLE public.curso_ufcd_formadores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full cuf" ON public.curso_ufcd_formadores FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- SESSOES (cronograma)
CREATE TABLE public.sessoes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_id UUID NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  curso_ufcd_id UUID NOT NULL REFERENCES public.curso_ufcds(id) ON DELETE CASCADE,
  formador_id UUID NOT NULL REFERENCES public.formadores(id) ON DELETE RESTRICT,
  data DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fim TIME NOT NULL,
  horas NUMERIC(5,2) NOT NULL,
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (hora_fim > hora_inicio)
);
CREATE INDEX idx_sessoes_curso_data ON public.sessoes(curso_id, data);
CREATE INDEX idx_sessoes_formador_data ON public.sessoes(formador_id, data);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sessoes TO authenticated;
GRANT ALL ON public.sessoes TO service_role;
ALTER TABLE public.sessoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full sessoes" ON public.sessoes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_sessoes_upd BEFORE UPDATE ON public.sessoes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
` },
  { name: "20260621195301_ebd382e4-b79a-4d34-b31e-764ba84c920b.sql", sql: `
CREATE POLICY "auth read formador-documentos" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'formador-documentos');
CREATE POLICY "auth insert formador-documentos" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'formador-documentos');
CREATE POLICY "auth update formador-documentos" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'formador-documentos') WITH CHECK (bucket_id = 'formador-documentos');
CREATE POLICY "auth delete formador-documentos" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'formador-documentos');
` },
  { name: "20260621203605_5d41e5b7-c538-4598-9fad-0124a1ec4a54.sql", sql: `
CREATE TYPE public.formando_estado AS ENUM ('ativo', 'inativo', 'desistente', 'concluido');
CREATE TYPE public.inscricao_estado AS ENUM ('inscrito', 'em_formacao', 'concluido', 'desistente');

CREATE TABLE public.formandos (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nome TEXT NOT NULL,
  nif TEXT,
  cc TEXT,
  validade_cc DATE,
  data_nascimento DATE,
  telemovel TEXT,
  email TEXT,
  morada TEXT,
  codigo_postal TEXT,
  localidade TEXT,
  habilitacoes TEXT,
  situacao_emprego TEXT,
  niss TEXT,
  observacoes TEXT,
  estado public.formando_estado NOT NULL DEFAULT 'ativo',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formandos TO authenticated;
GRANT ALL ON public.formandos TO service_role;
ALTER TABLE public.formandos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full formandos" ON public.formandos FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_formandos_updated_at BEFORE UPDATE ON public.formandos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.curso_formandos (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  curso_id UUID NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  formando_id UUID NOT NULL REFERENCES public.formandos(id) ON DELETE CASCADE,
  data_inscricao DATE NOT NULL DEFAULT CURRENT_DATE,
  estado public.inscricao_estado NOT NULL DEFAULT 'inscrito',
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (curso_id, formando_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.curso_formandos TO authenticated;
GRANT ALL ON public.curso_formandos TO service_role;
ALTER TABLE public.curso_formandos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full curso_formandos" ON public.curso_formandos FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX idx_curso_formandos_curso ON public.curso_formandos(curso_id);
CREATE INDEX idx_curso_formandos_formando ON public.curso_formandos(formando_id);
` },
  { name: "20260621204056_2b48b454-65de-4dbe-a14c-f7d8c607c50c.sql", sql: `
CREATE TYPE public.falta_tipo AS ENUM ('justificada', 'injustificada');

CREATE TABLE public.formando_faltas (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  curso_formando_id UUID NOT NULL REFERENCES public.curso_formandos(id) ON DELETE CASCADE,
  sessao_id UUID REFERENCES public.sessoes(id) ON DELETE SET NULL,
  data DATE NOT NULL,
  horas NUMERIC NOT NULL DEFAULT 0,
  tipo public.falta_tipo NOT NULL DEFAULT 'injustificada',
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formando_faltas TO authenticated;
GRANT ALL ON public.formando_faltas TO service_role;
ALTER TABLE public.formando_faltas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full faltas" ON public.formando_faltas FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX idx_faltas_cf ON public.formando_faltas(curso_formando_id);
CREATE INDEX idx_faltas_sessao ON public.formando_faltas(sessao_id);
` },
  { name: "20260621210055_a16125b5-ae9f-4fd3-9e7e-d67c51ed2d26.sql", sql: `
CREATE TABLE public.formador_disponibilidades (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  formador_id uuid NOT NULL REFERENCES public.formadores(id) ON DELETE CASCADE,
  data date NOT NULL,
  hora_inicio time NOT NULL DEFAULT '09:00',
  hora_fim time NOT NULL DEFAULT '18:00',
  tipo text NOT NULL DEFAULT 'disponivel' CHECK (tipo IN ('disponivel','indisponivel')),
  notas text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.formador_disponibilidades TO authenticated;
GRANT ALL ON public.formador_disponibilidades TO service_role;

ALTER TABLE public.formador_disponibilidades ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth full disponibilidades" ON public.formador_disponibilidades
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER set_updated_at_disp BEFORE UPDATE ON public.formador_disponibilidades
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_disp_formador_data ON public.formador_disponibilidades(formador_id, data);
` },
  { name: "20260621223501_ff570b55-e487-45ce-b8e2-6cb132452a1c.sql", sql: `ALTER TABLE public.formadores ADD COLUMN IF NOT EXISTS abreviatura text;

UPDATE public.formadores
SET abreviatura = CASE
  WHEN array_length(regexp_split_to_array(trim(nome), '\\s+'), 1) >= 2
    THEN (regexp_split_to_array(trim(nome), '\\s+'))[1]
      || ' '
      || (regexp_split_to_array(trim(nome), '\\s+'))[array_length(regexp_split_to_array(trim(nome), '\\s+'), 1)]
  ELSE trim(nome)
END
WHERE abreviatura IS NULL OR abreviatura = '';` },
  { name: "20260622121736_a535fa45-585f-4d38-9b0f-6cb99b0b22e9.sql", sql: `DO $$ BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.cursos; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.curso_ufcds; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.curso_ufcd_formadores; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.formador_disponibilidades; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.sessoes; EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;
ALTER TABLE public.cursos REPLICA IDENTITY FULL;
ALTER TABLE public.curso_ufcds REPLICA IDENTITY FULL;
ALTER TABLE public.curso_ufcd_formadores REPLICA IDENTITY FULL;
ALTER TABLE public.formador_disponibilidades REPLICA IDENTITY FULL;
ALTER TABLE public.sessoes REPLICA IDENTITY FULL;` },
  { name: "20260622144811_d479788a-69bf-435a-9524-5762b6e8d569.sql", sql: `ALTER TABLE public.formadores ADD COLUMN IF NOT EXISTS data_nascimento date;` },
  { name: "20260622153722_08ddb3d2-c42f-420f-afa5-6049bc73652c.sql", sql: `CREATE TABLE public.formador_ufcds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  formador_id uuid NOT NULL REFERENCES public.formadores(id) ON DELETE CASCADE,
  ufcd_id uuid NOT NULL REFERENCES public.ufcds(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (formador_id, ufcd_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formador_ufcds TO authenticated;
GRANT ALL ON public.formador_ufcds TO service_role;
ALTER TABLE public.formador_ufcds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full formador_ufcds" ON public.formador_ufcds FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE INDEX idx_formador_ufcds_formador ON public.formador_ufcds(formador_id);
CREATE INDEX idx_formador_ufcds_ufcd ON public.formador_ufcds(ufcd_id);` },
  { name: "20260624090416_b8981ed9-48f9-40e8-a9f6-65a7c3a7fdcc.sql", sql: `ALTER TABLE public.formador_disponibilidades ADD COLUMN IF NOT EXISTS curso_id uuid REFERENCES public.cursos(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_disp_curso ON public.formador_disponibilidades(curso_id);` },
  { name: "20260624121839_76f1789f-2d42-4619-8881-35ce7a0e118e.sql", sql: `
CREATE TABLE public.formando_pra (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_formando_id UUID NOT NULL REFERENCES public.curso_formandos(id) ON DELETE CASCADE,
  curso_ufcd_id UUID NOT NULL REFERENCES public.curso_ufcds(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(curso_formando_id, curso_ufcd_id)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.formando_pra TO authenticated;
GRANT ALL ON public.formando_pra TO service_role;

ALTER TABLE public.formando_pra ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth full formando_pra" ON public.formando_pra FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER trg_formando_pra_updated_at
BEFORE UPDATE ON public.formando_pra
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Storage policies for the formando-pra bucket (authenticated full access)
CREATE POLICY "auth read formando-pra"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'formando-pra');

CREATE POLICY "auth insert formando-pra"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'formando-pra');

CREATE POLICY "auth update formando-pra"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'formando-pra');

CREATE POLICY "auth delete formando-pra"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'formando-pra');
` },
  { name: "20260624123640_d3e879d5-8b5b-401d-81cd-09895902a3d6.sql", sql: `ALTER TABLE public.formando_pra ADD COLUMN IF NOT EXISTS nota TEXT;
ALTER TABLE public.formando_pra ALTER COLUMN nome DROP NOT NULL;
ALTER TABLE public.formando_pra ALTER COLUMN storage_path DROP NOT NULL;` },
  { name: "20260624170234_ebcb9db3-c682-440f-92e0-095cf4c95c63.sql", sql: `UPDATE public.sessoes
SET horas = GREATEST(0,
  EXTRACT(EPOCH FROM (hora_fim - hora_inicio))/3600.0
  - GREATEST(0, EXTRACT(EPOCH FROM (LEAST(hora_fim, TIME '14:00') - GREATEST(hora_inicio, TIME '13:00')))/3600.0)
)
WHERE hora_fim > hora_inicio;` },
  { name: "20260625120000_allow_sessoes_sem_formador.sql", sql: `-- Permite sessões sem formador para aparecerem no cronograma/impressão como "em falta".
ALTER TABLE public.sessoes
  ALTER COLUMN formador_id DROP NOT NULL;
` },
  { name: "20260625135321_7cebdd5e-efcf-453f-ba65-bfd56316c079.sql", sql: `CREATE TABLE public.curso_ferias (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  curso_id uuid NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  data_inicio date NOT NULL,
  data_fim date NOT NULL,
  motivo text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.curso_ferias TO authenticated;
GRANT ALL ON public.curso_ferias TO service_role;
ALTER TABLE public.curso_ferias ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full curso_ferias" ON public.curso_ferias TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER curso_ferias_updated BEFORE UPDATE ON public.curso_ferias FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE INDEX curso_ferias_curso_idx ON public.curso_ferias(curso_id, data_inicio, data_fim);` },
  { name: "20260629115806_228c1f42-e166-460a-88af-cda1df84cd7e.sql", sql: `CREATE TABLE public.cronograma_observacoes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_id uuid NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  mes date NOT NULL,
  texto text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (curso_id, mes)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cronograma_observacoes TO authenticated;
GRANT ALL ON public.cronograma_observacoes TO service_role;
ALTER TABLE public.cronograma_observacoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full cronograma_observacoes" ON public.cronograma_observacoes FOR ALL USING (true) WITH CHECK (true);` },
];
