// AUTO-GENERATED by scripts/bundle-migrations.mjs — do not edit by hand.
// Run `node scripts/bundle-migrations.mjs` whenever migrations change.
export type Migration = { name: string; sql: string };
export const MIGRATIONS: Migration[] = [
  { name: "20260621195230_2b87c4d8-afaa-413e-a6e0-b54a34fc46a5.sql", sql: `
-- Enums
CREATE TYPE public.formador_estado AS ENUM ('ativo','inativo','ferias','baixa_medica','suspenso','arquivado');
CREATE TYPE public.curso_tipologia AS ENUM ('EFA','ERFA','MFA','OUTRO');
CREATE TYPE public.curso_estado AS ENUM ('planeado','ativo','concluido','suspenso','cancelado');

-- Trigger function for updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

-- FORMADORES
CREATE TABLE public.formadores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT NOT NULL,
  nif TEXT,
  cc TEXT,
  validade_cc DATE,
  morada TEXT,
  codigo_postal TEXT,
  localidade TEXT,
  telemovel TEXT,
  email TEXT,
  iban TEXT,
  habilitacoes TEXT,
  ccp TEXT,
  validade_ccp DATE,
  observacoes TEXT,
  estado public.formador_estado NOT NULL DEFAULT 'ativo',
  cor TEXT NOT NULL DEFAULT '#E11D48',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formadores TO authenticated;
GRANT ALL ON public.formadores TO service_role;
ALTER TABLE public.formadores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full access formadores" ON public.formadores FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_formadores_upd BEFORE UPDATE ON public.formadores FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- INATIVIDADES
CREATE TABLE public.formador_inatividades (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  formador_id UUID NOT NULL REFERENCES public.formadores(id) ON DELETE CASCADE,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  motivo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formador_inatividades TO authenticated;
GRANT ALL ON public.formador_inatividades TO service_role;
ALTER TABLE public.formador_inatividades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full inatividades" ON public.formador_inatividades FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- DOCUMENTOS
CREATE TABLE public.formador_documentos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  formador_id UUID NOT NULL REFERENCES public.formadores(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL,
  nome TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  validade DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formador_documentos TO authenticated;
GRANT ALL ON public.formador_documentos TO service_role;
ALTER TABLE public.formador_documentos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full documentos" ON public.formador_documentos FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- CURSOS
CREATE TABLE public.cursos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo TEXT NOT NULL,
  nome TEXT NOT NULL,
  tipologia public.curso_tipologia NOT NULL DEFAULT 'EFA',
  data_inicio DATE,
  data_fim DATE,
  estado public.curso_estado NOT NULL DEFAULT 'planeado',
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cursos TO authenticated;
GRANT ALL ON public.cursos TO service_role;
ALTER TABLE public.cursos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full cursos" ON public.cursos FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_cursos_upd BEFORE UPDATE ON public.cursos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- UFCDs (catalogo)
CREATE TABLE public.ufcds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo TEXT NOT NULL UNIQUE,
  designacao TEXT NOT NULL,
  horas_referencia INTEGER NOT NULL DEFAULT 25,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ufcds TO authenticated;
GRANT ALL ON public.ufcds TO service_role;
ALTER TABLE public.ufcds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full ufcds" ON public.ufcds FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- CURSO_UFCDS (UFCD atribuida a curso)
CREATE TABLE public.curso_ufcds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_id UUID NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  ufcd_id UUID NOT NULL REFERENCES public.ufcds(id) ON DELETE RESTRICT,
  horas_totais INTEGER NOT NULL DEFAULT 25,
  ordem INTEGER NOT NULL DEFAULT 0,
  concluida BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (curso_id, ufcd_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.curso_ufcds TO authenticated;
GRANT ALL ON public.curso_ufcds TO service_role;
ALTER TABLE public.curso_ufcds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full curso_ufcds" ON public.curso_ufcds FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- CURSO_UFCD_FORMADORES
CREATE TABLE public.curso_ufcd_formadores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_ufcd_id UUID NOT NULL REFERENCES public.curso_ufcds(id) ON DELETE CASCADE,
  formador_id UUID NOT NULL REFERENCES public.formadores(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (curso_ufcd_id, formador_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.curso_ufcd_formadores TO authenticated;
GRANT ALL ON public.curso_ufcd_formadores TO service_role;
ALTER TABLE public.curso_ufcd_formadores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full cuf" ON public.curso_ufcd_formadores FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- SESSOES (cronograma)
CREATE TABLE public.sessoes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_id UUID NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  curso_ufcd_id UUID NOT NULL REFERENCES public.curso_ufcds(id) ON DELETE CASCADE,
  formador_id UUID NOT NULL REFERENCES public.formadores(id) ON DELETE RESTRICT,
  data DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fim TIME NOT NULL,
  horas NUMERIC(5,2) NOT NULL,
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (hora_fim > hora_inicio)
);
CREATE INDEX idx_sessoes_curso_data ON public.sessoes(curso_id, data);
CREATE INDEX idx_sessoes_formador_data ON public.sessoes(formador_id, data);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sessoes TO authenticated;
GRANT ALL ON public.sessoes TO service_role;
ALTER TABLE public.sessoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full sessoes" ON public.sessoes FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_sessoes_upd BEFORE UPDATE ON public.sessoes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
` },
  { name: "20260621195301_ebd382e4-b79a-4d34-b31e-764ba84c920b.sql", sql: `
CREATE POLICY "auth read formador-documentos" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'formador-documentos');
CREATE POLICY "auth insert formador-documentos" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'formador-documentos');
CREATE POLICY "auth update formador-documentos" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'formador-documentos') WITH CHECK (bucket_id = 'formador-documentos');
CREATE POLICY "auth delete formador-documentos" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'formador-documentos');
` },
  { name: "20260621203605_5d41e5b7-c538-4598-9fad-0124a1ec4a54.sql", sql: `
CREATE TYPE public.formando_estado AS ENUM ('ativo', 'inativo', 'desistente', 'concluido');
CREATE TYPE public.inscricao_estado AS ENUM ('inscrito', 'em_formacao', 'concluido', 'desistente');

CREATE TABLE public.formandos (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nome TEXT NOT NULL,
  nif TEXT,
  cc TEXT,
  validade_cc DATE,
  data_nascimento DATE,
  telemovel TEXT,
  email TEXT,
  morada TEXT,
  codigo_postal TEXT,
  localidade TEXT,
  habilitacoes TEXT,
  situacao_emprego TEXT,
  niss TEXT,
  observacoes TEXT,
  estado public.formando_estado NOT NULL DEFAULT 'ativo',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formandos TO authenticated;
GRANT ALL ON public.formandos TO service_role;
ALTER TABLE public.formandos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full formandos" ON public.formandos FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_formandos_updated_at BEFORE UPDATE ON public.formandos FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.curso_formandos (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  curso_id UUID NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  formando_id UUID NOT NULL REFERENCES public.formandos(id) ON DELETE CASCADE,
  data_inscricao DATE NOT NULL DEFAULT CURRENT_DATE,
  estado public.inscricao_estado NOT NULL DEFAULT 'inscrito',
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (curso_id, formando_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.curso_formandos TO authenticated;
GRANT ALL ON public.curso_formandos TO service_role;
ALTER TABLE public.curso_formandos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full curso_formandos" ON public.curso_formandos FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX idx_curso_formandos_curso ON public.curso_formandos(curso_id);
CREATE INDEX idx_curso_formandos_formando ON public.curso_formandos(formando_id);
` },
  { name: "20260621204056_2b48b454-65de-4dbe-a14c-f7d8c607c50c.sql", sql: `
CREATE TYPE public.falta_tipo AS ENUM ('justificada', 'injustificada');

CREATE TABLE public.formando_faltas (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  curso_formando_id UUID NOT NULL REFERENCES public.curso_formandos(id) ON DELETE CASCADE,
  sessao_id UUID REFERENCES public.sessoes(id) ON DELETE SET NULL,
  data DATE NOT NULL,
  horas NUMERIC NOT NULL DEFAULT 0,
  tipo public.falta_tipo NOT NULL DEFAULT 'injustificada',
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formando_faltas TO authenticated;
GRANT ALL ON public.formando_faltas TO service_role;
ALTER TABLE public.formando_faltas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full faltas" ON public.formando_faltas FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX idx_faltas_cf ON public.formando_faltas(curso_formando_id);
CREATE INDEX idx_faltas_sessao ON public.formando_faltas(sessao_id);
` },
  { name: "20260621210055_a16125b5-ae9f-4fd3-9e7e-d67c51ed2d26.sql", sql: `
CREATE TABLE public.formador_disponibilidades (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  formador_id uuid NOT NULL REFERENCES public.formadores(id) ON DELETE CASCADE,
  data date NOT NULL,
  hora_inicio time NOT NULL DEFAULT '09:00',
  hora_fim time NOT NULL DEFAULT '18:00',
  tipo text NOT NULL DEFAULT 'disponivel' CHECK (tipo IN ('disponivel','indisponivel')),
  notas text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.formador_disponibilidades TO authenticated;
GRANT ALL ON public.formador_disponibilidades TO service_role;

ALTER TABLE public.formador_disponibilidades ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth full disponibilidades" ON public.formador_disponibilidades
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER set_updated_at_disp BEFORE UPDATE ON public.formador_disponibilidades
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_disp_formador_data ON public.formador_disponibilidades(formador_id, data);
` },
  { name: "20260621223501_ff570b55-e487-45ce-b8e2-6cb132452a1c.sql", sql: `ALTER TABLE public.formadores ADD COLUMN IF NOT EXISTS abreviatura text;

UPDATE public.formadores
SET abreviatura = CASE
  WHEN array_length(regexp_split_to_array(trim(nome), '\\s+'), 1) >= 2
    THEN (regexp_split_to_array(trim(nome), '\\s+'))[1]
      || ' '
      || (regexp_split_to_array(trim(nome), '\\s+'))[array_length(regexp_split_to_array(trim(nome), '\\s+'), 1)]
  ELSE trim(nome)
END
WHERE abreviatura IS NULL OR abreviatura = '';` },
  { name: "20260622121736_a535fa45-585f-4d38-9b0f-6cb99b0b22e9.sql", sql: `DO $$ BEGIN
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.cursos; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.curso_ufcds; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.curso_ufcd_formadores; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.formador_disponibilidades; EXCEPTION WHEN duplicate_object THEN NULL; END;
  BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE public.sessoes; EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;
ALTER TABLE public.cursos REPLICA IDENTITY FULL;
ALTER TABLE public.curso_ufcds REPLICA IDENTITY FULL;
ALTER TABLE public.curso_ufcd_formadores REPLICA IDENTITY FULL;
ALTER TABLE public.formador_disponibilidades REPLICA IDENTITY FULL;
ALTER TABLE public.sessoes REPLICA IDENTITY FULL;` },
  { name: "20260622144811_d479788a-69bf-435a-9524-5762b6e8d569.sql", sql: `ALTER TABLE public.formadores ADD COLUMN IF NOT EXISTS data_nascimento date;` },
  { name: "20260622153722_08ddb3d2-c42f-420f-afa5-6049bc73652c.sql", sql: `CREATE TABLE public.formador_ufcds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  formador_id uuid NOT NULL REFERENCES public.formadores(id) ON DELETE CASCADE,
  ufcd_id uuid NOT NULL REFERENCES public.ufcds(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (formador_id, ufcd_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.formador_ufcds TO authenticated;
GRANT ALL ON public.formador_ufcds TO service_role;
ALTER TABLE public.formador_ufcds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full formador_ufcds" ON public.formador_ufcds FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE INDEX idx_formador_ufcds_formador ON public.formador_ufcds(formador_id);
CREATE INDEX idx_formador_ufcds_ufcd ON public.formador_ufcds(ufcd_id);` },
  { name: "20260624090416_b8981ed9-48f9-40e8-a9f6-65a7c3a7fdcc.sql", sql: `ALTER TABLE public.formador_disponibilidades ADD COLUMN IF NOT EXISTS curso_id uuid REFERENCES public.cursos(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_disp_curso ON public.formador_disponibilidades(curso_id);` },
  { name: "20260624121839_76f1789f-2d42-4619-8881-35ce7a0e118e.sql", sql: `
CREATE TABLE public.formando_pra (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_formando_id UUID NOT NULL REFERENCES public.curso_formandos(id) ON DELETE CASCADE,
  curso_ufcd_id UUID NOT NULL REFERENCES public.curso_ufcds(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(curso_formando_id, curso_ufcd_id)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.formando_pra TO authenticated;
GRANT ALL ON public.formando_pra TO service_role;

ALTER TABLE public.formando_pra ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth full formando_pra" ON public.formando_pra FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER trg_formando_pra_updated_at
BEFORE UPDATE ON public.formando_pra
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Storage policies for the formando-pra bucket (authenticated full access)
CREATE POLICY "auth read formando-pra"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'formando-pra');

CREATE POLICY "auth insert formando-pra"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'formando-pra');

CREATE POLICY "auth update formando-pra"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id = 'formando-pra');

CREATE POLICY "auth delete formando-pra"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'formando-pra');
` },
  { name: "20260624123640_d3e879d5-8b5b-401d-81cd-09895902a3d6.sql", sql: `ALTER TABLE public.formando_pra ADD COLUMN IF NOT EXISTS nota TEXT;
ALTER TABLE public.formando_pra ALTER COLUMN nome DROP NOT NULL;
ALTER TABLE public.formando_pra ALTER COLUMN storage_path DROP NOT NULL;` },
  { name: "20260624170234_ebcb9db3-c682-440f-92e0-095cf4c95c63.sql", sql: `UPDATE public.sessoes
SET horas = GREATEST(0,
  EXTRACT(EPOCH FROM (hora_fim - hora_inicio))/3600.0
  - GREATEST(0, EXTRACT(EPOCH FROM (LEAST(hora_fim, TIME '14:00') - GREATEST(hora_inicio, TIME '13:00')))/3600.0)
)
WHERE hora_fim > hora_inicio;` },
  { name: "20260625120000_allow_sessoes_sem_formador.sql", sql: `-- Permite sessões sem formador para aparecerem no cronograma/impressão como "em falta".
ALTER TABLE public.sessoes
  ALTER COLUMN formador_id DROP NOT NULL;
` },
  { name: "20260625135321_7cebdd5e-efcf-453f-ba65-bfd56316c079.sql", sql: `CREATE TABLE public.curso_ferias (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  curso_id uuid NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  data_inicio date NOT NULL,
  data_fim date NOT NULL,
  motivo text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.curso_ferias TO authenticated;
GRANT ALL ON public.curso_ferias TO service_role;
ALTER TABLE public.curso_ferias ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full curso_ferias" ON public.curso_ferias TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER curso_ferias_updated BEFORE UPDATE ON public.curso_ferias FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE INDEX curso_ferias_curso_idx ON public.curso_ferias(curso_id, data_inicio, data_fim);` },
  { name: "20260629115806_228c1f42-e166-460a-88af-cda1df84cd7e.sql", sql: `CREATE TABLE public.cronograma_observacoes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_id uuid NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  mes date NOT NULL,
  texto text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (curso_id, mes)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cronograma_observacoes TO authenticated;
GRANT ALL ON public.cronograma_observacoes TO service_role;
ALTER TABLE public.cronograma_observacoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full cronograma_observacoes" ON public.cronograma_observacoes FOR ALL USING (true) WITH CHECK (true);` },
  { name: "20260701105540_b79c605b-3bfb-452b-88b5-c9ce7c921541.sql", sql: `CREATE TABLE public.curso_formando_ufcds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  curso_formando_id uuid NOT NULL REFERENCES public.curso_formandos(id) ON DELETE CASCADE,
  curso_ufcd_id uuid NOT NULL REFERENCES public.curso_ufcds(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(curso_formando_id, curso_ufcd_id)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.curso_formando_ufcds TO authenticated;
GRANT ALL ON public.curso_formando_ufcds TO service_role;

ALTER TABLE public.curso_formando_ufcds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth all" ON public.curso_formando_ufcds FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE INDEX idx_cfu_cf ON public.curso_formando_ufcds(curso_formando_id);
CREATE INDEX idx_cfu_cu ON public.curso_formando_ufcds(curso_ufcd_id);` },
  { name: "20260718214915_c12dc329-cab3-4dc9-a2d5-84577be21e01.sql", sql: `
-- Financeiro module
CREATE TABLE public.financeiro_processamentos (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  curso_id UUID NOT NULL REFERENCES public.cursos(id) ON DELETE CASCADE,
  ano INTEGER NOT NULL,
  mes INTEGER NOT NULL CHECK (mes BETWEEN 1 AND 12),
  estado TEXT NOT NULL DEFAULT 'aberto' CHECK (estado IN ('aberto','fechado')),
  data_criacao TIMESTAMPTZ NOT NULL DEFAULT now(),
  data_fecho TIMESTAMPTZ,
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (curso_id, ano, mes)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.financeiro_processamentos TO authenticated;
GRANT ALL ON public.financeiro_processamentos TO service_role;
ALTER TABLE public.financeiro_processamentos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth all processamentos" ON public.financeiro_processamentos FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.financeiro_bolsas (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  processamento_id UUID NOT NULL REFERENCES public.financeiro_processamentos(id) ON DELETE CASCADE,
  formando_id UUID NOT NULL REFERENCES public.formandos(id) ON DELETE CASCADE,
  horas_previstas NUMERIC(8,2) NOT NULL DEFAULT 0,
  horas_frequentadas NUMERIC(8,2) NOT NULL DEFAULT 0,
  valor_hora NUMERIC(10,4) NOT NULL DEFAULT 0,
  valor_calculado NUMERIC(12,2) NOT NULL DEFAULT 0,
  valor_final NUMERIC(12,2) NOT NULL DEFAULT 0,
  editado_manual BOOLEAN NOT NULL DEFAULT false,
  observacoes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.financeiro_bolsas TO authenticated;
GRANT ALL ON public.financeiro_bolsas TO service_role;
ALTER TABLE public.financeiro_bolsas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth all bolsas" ON public.financeiro_bolsas FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.financeiro_subsidios (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  processamento_id UUID NOT NULL REFERENCES public.financeiro_processamentos(id) ON DELETE CASCADE,
  formando_id UUID NOT NULL REFERENCES public.formandos(id) ON DELETE CASCADE,
  dias INTEGER NOT NULL DEFAULT 0,
  valor_dia NUMERIC(10,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.financeiro_subsidios TO authenticated;
GRANT ALL ON public.financeiro_subsidios TO service_role;
ALTER TABLE public.financeiro_subsidios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth all subsidios" ON public.financeiro_subsidios FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.financeiro_quilometros (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  processamento_id UUID NOT NULL REFERENCES public.financeiro_processamentos(id) ON DELETE CASCADE,
  formando_id UUID NOT NULL REFERENCES public.formandos(id) ON DELETE CASCADE,
  data DATE NOT NULL,
  origem TEXT,
  destino TEXT,
  km NUMERIC(10,2) NOT NULL DEFAULT 0,
  valor_km NUMERIC(10,4) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.financeiro_quilometros TO authenticated;
GRANT ALL ON public.financeiro_quilometros TO service_role;
ALTER TABLE public.financeiro_quilometros ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth all quilometros" ON public.financeiro_quilometros FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.financeiro_honorarios (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  processamento_id UUID NOT NULL REFERENCES public.financeiro_processamentos(id) ON DELETE CASCADE,
  formador_id UUID REFERENCES public.formadores(id) ON DELETE SET NULL,
  descricao TEXT,
  valor NUMERIC(12,2) NOT NULL DEFAULT 0,
  iva NUMERIC(5,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.financeiro_honorarios TO authenticated;
GRANT ALL ON public.financeiro_honorarios TO service_role;
ALTER TABLE public.financeiro_honorarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth all honorarios" ON public.financeiro_honorarios FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.configuracao_financeira (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  valor_refeicao NUMERIC(10,2) NOT NULL DEFAULT 6.00,
  valor_km NUMERIC(10,4) NOT NULL DEFAULT 0.40,
  horas_mes NUMERIC(8,2) NOT NULL DEFAULT 150,
  iva NUMERIC(5,2) NOT NULL DEFAULT 23,
  moeda TEXT NOT NULL DEFAULT 'EUR',
  atualizacao TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.configuracao_financeira TO authenticated;
GRANT ALL ON public.configuracao_financeira TO service_role;
ALTER TABLE public.configuracao_financeira ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth all config fin" ON public.configuracao_financeira FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- updated_at trigger (reuse if it exists, else create)
CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql SET search_path = public;

CREATE TRIGGER trg_fp_upd BEFORE UPDATE ON public.financeiro_processamentos FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_fb_upd BEFORE UPDATE ON public.financeiro_bolsas FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_fs_upd BEFORE UPDATE ON public.financeiro_subsidios FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_fq_upd BEFORE UPDATE ON public.financeiro_quilometros FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_fh_upd BEFORE UPDATE ON public.financeiro_honorarios FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER trg_cf_upd BEFORE UPDATE ON public.configuracao_financeira FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- seed default configuration row
INSERT INTO public.configuracao_financeira (valor_refeicao, valor_km, horas_mes, iva, moeda)
VALUES (6.00, 0.40, 150, 23, 'EUR');
` },
  { name: "20260720090742_46b5eb53-8f33-4f5d-be89-d517c3bf1bcc.sql", sql: `
-- ============================================================
-- Financeiro v2 — arquitetura base (Fase 1 alargada)
-- ============================================================

-- 1) UTILIZADORES locais (independente do auth do Supabase)
CREATE TABLE IF NOT EXISTS public.fin_utilizadores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  nome_utilizador text NOT NULL UNIQUE,
  perfil text NOT NULL DEFAULT 'operador',
  ativo boolean NOT NULL DEFAULT true,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_utilizadores TO authenticated;
GRANT ALL ON public.fin_utilizadores TO service_role;
ALTER TABLE public.fin_utilizadores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full fin_utilizadores" ON public.fin_utilizadores FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_fin_utilizadores_upd BEFORE UPDATE ON public.fin_utilizadores FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 2) CONFIGURAÇÃO GLOBAL versionada (nunca apagar — mantém histórico)
CREATE TABLE IF NOT EXISTS public.fin_configuracao_global (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  horas_mes_referencia numeric NOT NULL DEFAULT 150,
  valor_subsidio_alimentacao numeric NOT NULL DEFAULT 6.00,
  valor_km numeric NOT NULL DEFAULT 0.40,
  moeda text NOT NULL DEFAULT 'EUR',
  casas_decimais smallint NOT NULL DEFAULT 2,
  data_inicio date NOT NULL DEFAULT CURRENT_DATE,
  utilizador_id uuid REFERENCES public.fin_utilizadores(id) ON DELETE SET NULL,
  utilizador_nome text,
  observacoes text,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_configuracao_global TO authenticated;
GRANT ALL ON public.fin_configuracao_global TO service_role;
ALTER TABLE public.fin_configuracao_global ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full fin_configuracao_global" ON public.fin_configuracao_global FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_fin_cfg_global_upd BEFORE UPDATE ON public.fin_configuracao_global FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE INDEX IF NOT EXISTS idx_fin_cfg_global_inicio ON public.fin_configuracao_global(data_inicio DESC);

-- 3) RUBRICAS FINANCEIRAS (catálogo)
CREATE TABLE IF NOT EXISTS public.fin_rubricas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo text NOT NULL UNIQUE,
  descricao text NOT NULL,
  categoria text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  ordem integer NOT NULL DEFAULT 100,
  permite_edicao_manual boolean NOT NULL DEFAULT true,
  gera_documento boolean NOT NULL DEFAULT false,
  gera_exportacao boolean NOT NULL DEFAULT true,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_rubricas TO authenticated;
GRANT ALL ON public.fin_rubricas TO service_role;
ALTER TABLE public.fin_rubricas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full fin_rubricas" ON public.fin_rubricas FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_fin_rubricas_upd BEFORE UPDATE ON public.fin_rubricas FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 4) REGRAS das rubricas (versionadas por período)
CREATE TABLE IF NOT EXISTS public.fin_rubrica_regras (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rubrica_id uuid NOT NULL REFERENCES public.fin_rubricas(id) ON DELETE CASCADE,
  valor_unitario numeric,
  valor_maximo numeric,
  horas_referencia numeric,
  dias_minimos integer,
  permite_limite boolean NOT NULL DEFAULT false,
  permite_edicao_manual boolean NOT NULL DEFAULT true,
  ativo boolean NOT NULL DEFAULT true,
  data_inicio date NOT NULL DEFAULT CURRENT_DATE,
  data_fim date,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_rubrica_regras TO authenticated;
GRANT ALL ON public.fin_rubrica_regras TO service_role;
ALTER TABLE public.fin_rubrica_regras ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full fin_rubrica_regras" ON public.fin_rubrica_regras FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_fin_regras_upd BEFORE UPDATE ON public.fin_rubrica_regras FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE INDEX IF NOT EXISTS idx_fin_regras_rubrica ON public.fin_rubrica_regras(rubrica_id, data_inicio DESC);

-- 5) FORMANDO — rubricas configuradas (elegibilidade + overrides)
CREATE TABLE IF NOT EXISTS public.fin_formando_rubricas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  formando_id uuid NOT NULL REFERENCES public.formandos(id) ON DELETE CASCADE,
  rubrica_id uuid NOT NULL REFERENCES public.fin_rubricas(id) ON DELETE CASCADE,
  elegivel boolean NOT NULL DEFAULT true,
  valor_especifico numeric,
  limite_especifico numeric,
  data_inicio date,
  data_fim date,
  iban text,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (formando_id, rubrica_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_formando_rubricas TO authenticated;
GRANT ALL ON public.fin_formando_rubricas TO service_role;
ALTER TABLE public.fin_formando_rubricas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full fin_formando_rubricas" ON public.fin_formando_rubricas FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_fin_fr_upd BEFORE UPDATE ON public.fin_formando_rubricas FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE INDEX IF NOT EXISTS idx_fin_fr_formando ON public.fin_formando_rubricas(formando_id);

-- 6) FORMADOR — configuração fiscal para honorários
CREATE TABLE IF NOT EXISTS public.fin_formador_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  formador_id uuid NOT NULL UNIQUE REFERENCES public.formadores(id) ON DELETE CASCADE,
  regime_iva text NOT NULL DEFAULT 'isento',
  artigo_isencao text,
  retencao_irs boolean NOT NULL DEFAULT true,
  percentagem_irs numeric NOT NULL DEFAULT 23,
  seguranca_social boolean NOT NULL DEFAULT false,
  percentagem_ss numeric,
  iban text,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_formador_config TO authenticated;
GRANT ALL ON public.fin_formador_config TO service_role;
ALTER TABLE public.fin_formador_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full fin_formador_config" ON public.fin_formador_config FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER trg_fin_fc_upd BEFORE UPDATE ON public.fin_formador_config FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 7) AUDITORIA financeira
CREATE TABLE IF NOT EXISTS public.fin_auditoria (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  utilizador_id uuid REFERENCES public.fin_utilizadores(id) ON DELETE SET NULL,
  nome_utilizador text NOT NULL,
  operacao text NOT NULL,
  entidade text NOT NULL,
  registo_id uuid,
  campo_alterado text,
  valor_anterior text,
  valor_novo text,
  motivo text,
  data_hora timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fin_auditoria TO authenticated;
GRANT ALL ON public.fin_auditoria TO service_role;
ALTER TABLE public.fin_auditoria ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth full fin_auditoria" ON public.fin_auditoria FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE INDEX IF NOT EXISTS idx_fin_auditoria_entidade ON public.fin_auditoria(entidade, registo_id, data_hora DESC);

-- Seed inicial de rubricas
INSERT INTO public.fin_rubricas (codigo, descricao, categoria, ordem, gera_documento, gera_exportacao) VALUES
  ('BF1', 'Bolsa de Formação — Tipo 1', 'Bolsa', 10, false, true),
  ('BF2', 'Bolsa de Formação — Tipo 2', 'Bolsa', 20, false, true),
  ('BFM', 'Bolsa Majorada',              'Bolsa', 30, false, true),
  ('SA',  'Subsídio de Alimentação',     'Subsídio', 40, false, true),
  ('KM',  'Quilómetros / Deslocação',    'Deslocação', 50, false, true),
  ('HON', 'Honorários de Formador',      'Honorários', 60, true,  true),
  ('OUT', 'Outros',                      'Outros', 90, false, true)
ON CONFLICT (codigo) DO NOTHING;
` },
  { name: "20260720113907_2dfd0d33-c3d1-4154-a25f-aeb55e830489.sql", sql: `
-- 1) Tabela projetos
CREATE TYPE public.projeto_estado AS ENUM ('planeado','ativo','concluido','arquivado');

CREATE TABLE public.projetos (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  codigo text NOT NULL UNIQUE,
  nome text NOT NULL,
  descricao text,
  entidade_promotora text,
  programa_financiamento text,
  data_inicio date,
  data_fim date,
  estado public.projeto_estado NOT NULL DEFAULT 'ativo',
  ativo boolean NOT NULL DEFAULT true,
  observacoes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.projetos TO authenticated;
GRANT ALL ON public.projetos TO service_role;
ALTER TABLE public.projetos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "projetos leitura autenticada" ON public.projetos FOR SELECT TO authenticated USING (true);
CREATE POLICY "projetos escrita autenticada" ON public.projetos FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER trg_projetos_updated_at BEFORE UPDATE ON public.projetos
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- 2) Projeto por defeito para migração
INSERT INTO public.projetos (codigo, nome, descricao, estado)
VALUES ('DEFAULT', 'Projeto principal', 'Projeto criado automaticamente para dados existentes.', 'ativo');

-- 3) cursos.projeto_id
ALTER TABLE public.cursos ADD COLUMN projeto_id uuid REFERENCES public.projetos(id) ON DELETE RESTRICT;
UPDATE public.cursos SET projeto_id = (SELECT id FROM public.projetos WHERE codigo='DEFAULT') WHERE projeto_id IS NULL;
CREATE INDEX idx_cursos_projeto_id ON public.cursos(projeto_id);

-- 4) financeiro_processamentos.projeto_id
ALTER TABLE public.financeiro_processamentos ADD COLUMN projeto_id uuid REFERENCES public.projetos(id) ON DELETE RESTRICT;
UPDATE public.financeiro_processamentos p
SET projeto_id = COALESCE(
  (SELECT c.projeto_id FROM public.cursos c WHERE c.id = p.curso_id),
  (SELECT id FROM public.projetos WHERE codigo='DEFAULT')
) WHERE projeto_id IS NULL;
CREATE INDEX idx_fin_proc_projeto_id ON public.financeiro_processamentos(projeto_id);
` },
  { name: "20260720115424_2c8ed882-d977-4564-8556-c399b36f51e6.sql", sql: `
-- 1) Processamentos: novo estado + colunas de totais e snapshot
ALTER TABLE public.financeiro_processamentos
  DROP CONSTRAINT IF EXISTS financeiro_processamentos_estado_check;
ALTER TABLE public.financeiro_processamentos
  ADD CONSTRAINT financeiro_processamentos_estado_check
  CHECK (estado IN ('aberto','calculado','fechado'));

ALTER TABLE public.financeiro_processamentos
  ADD COLUMN IF NOT EXISTS fechado_por text,
  ADD COLUMN IF NOT EXISTS total_bolsas numeric(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_subsidios numeric(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_km numeric(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_honorarios numeric(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_geral numeric(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS snapshot jsonb;

-- 2) Linhas: valor aprovado + memória de cálculo (+ teto na bolsa)
ALTER TABLE public.financeiro_bolsas
  ADD COLUMN IF NOT EXISTS valor_aprovado numeric(12,2),
  ADD COLUMN IF NOT EXISTS teto_aplicado boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS memoria_calculo jsonb;

ALTER TABLE public.financeiro_subsidios
  ADD COLUMN IF NOT EXISTS valor_aprovado numeric(12,2),
  ADD COLUMN IF NOT EXISTS memoria_calculo jsonb;

ALTER TABLE public.financeiro_quilometros
  ADD COLUMN IF NOT EXISTS valor_aprovado numeric(12,2),
  ADD COLUMN IF NOT EXISTS memoria_calculo jsonb;

ALTER TABLE public.financeiro_honorarios
  ADD COLUMN IF NOT EXISTS valor_aprovado numeric(12,2),
  ADD COLUMN IF NOT EXISTS horas numeric(8,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valor_hora numeric(10,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS retencao_irs numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS seguranca_social numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS memoria_calculo jsonb;

-- 3) Trigger de bloqueio: impede alterações em linhas de processamento fechado
CREATE OR REPLACE FUNCTION public.fin_bloqueio_fechado()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_estado text;
  v_proc_id uuid;
BEGIN
  v_proc_id := COALESCE(NEW.processamento_id, OLD.processamento_id);
  SELECT estado INTO v_estado FROM public.financeiro_processamentos WHERE id = v_proc_id;
  IF v_estado = 'fechado' THEN
    RAISE EXCEPTION 'Processamento fechado — alteracoes bloqueadas (%).', TG_TABLE_NAME
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN COALESCE(NEW, OLD);
END $$;

DROP TRIGGER IF EXISTS trg_fb_bloqueio ON public.financeiro_bolsas;
CREATE TRIGGER trg_fb_bloqueio BEFORE UPDATE OR DELETE ON public.financeiro_bolsas
  FOR EACH ROW EXECUTE FUNCTION public.fin_bloqueio_fechado();

DROP TRIGGER IF EXISTS trg_fs_bloqueio ON public.financeiro_subsidios;
CREATE TRIGGER trg_fs_bloqueio BEFORE UPDATE OR DELETE ON public.financeiro_subsidios
  FOR EACH ROW EXECUTE FUNCTION public.fin_bloqueio_fechado();

DROP TRIGGER IF EXISTS trg_fq_bloqueio ON public.financeiro_quilometros;
CREATE TRIGGER trg_fq_bloqueio BEFORE UPDATE OR DELETE ON public.financeiro_quilometros
  FOR EACH ROW EXECUTE FUNCTION public.fin_bloqueio_fechado();

DROP TRIGGER IF EXISTS trg_fh_bloqueio ON public.financeiro_honorarios;
CREATE TRIGGER trg_fh_bloqueio BEFORE UPDATE OR DELETE ON public.financeiro_honorarios
  FOR EACH ROW EXECUTE FUNCTION public.fin_bloqueio_fechado();

-- 4) Seed condicional
DO $$
DECLARE
  v_bf1 uuid; v_bf2 uuid; v_bfm uuid; v_sa uuid; v_km uuid; v_hon uuid;
BEGIN
  IF (SELECT count(*) FROM public.fin_rubricas) = 0 THEN
    INSERT INTO public.fin_rubricas (codigo, descricao, categoria, ordem, gera_documento, gera_exportacao)
      VALUES ('BF1','Bolsa Formacao Tipo 1','Bolsa',10,false,true) RETURNING id INTO v_bf1;
    INSERT INTO public.fin_rubricas (codigo, descricao, categoria, ordem, gera_documento, gera_exportacao)
      VALUES ('BF2','Bolsa Formacao Tipo 2','Bolsa',20,false,true) RETURNING id INTO v_bf2;
    INSERT INTO public.fin_rubricas (codigo, descricao, categoria, ordem, gera_documento, gera_exportacao)
      VALUES ('BFM','Bolsa Formacao Majorada','Bolsa',30,false,true) RETURNING id INTO v_bfm;
    INSERT INTO public.fin_rubricas (codigo, descricao, categoria, ordem, gera_documento, gera_exportacao)
      VALUES ('SA','Subsidio de Alimentacao','Subsídio',40,false,true) RETURNING id INTO v_sa;
    INSERT INTO public.fin_rubricas (codigo, descricao, categoria, ordem, gera_documento, gera_exportacao)
      VALUES ('KM','Quilometros','Deslocação',50,false,true) RETURNING id INTO v_km;
    INSERT INTO public.fin_rubricas (codigo, descricao, categoria, ordem, gera_documento, gera_exportacao, permite_edicao_manual)
      VALUES ('HON','Honorarios','Honorários',60,true,true,true) RETURNING id INTO v_hon;

    -- Regras exemplo (valores parametrizáveis via /financeiro/regras)
    INSERT INTO public.fin_rubrica_regras (rubrica_id, valor_unitario, valor_maximo, horas_referencia, permite_limite, observacoes)
      VALUES
      (v_bf1, 2.00, 200.00, 175, true, 'Seed exemplo. Editar em Regras.'),
      (v_bf2, 2.50, 250.00, 175, true, 'Seed exemplo. Editar em Regras.'),
      (v_bfm, 3.00, 300.00, 175, true, 'Seed exemplo. Editar em Regras.'),
      (v_sa,  6.00, NULL,   NULL, false, 'Valor diario. Dias minimos por dia definidos na regra.'),
      (v_km,  0.36, 150.00, NULL, true, 'Valor por Km (ida e volta). Teto mensal.'),
      (v_hon, 25.00, NULL,  NULL, false, 'Valor/hora base para honorarios avulsos.');

    -- dias_minimos por presença diária para o subsídio de alimentação
    UPDATE public.fin_rubrica_regras SET dias_minimos = 3 WHERE rubrica_id = v_sa;
  END IF;
END $$;
` },
  { name: "20260720130751_9d96bbf4-4a7e-475d-850b-22484b6f1e5c.sql", sql: `DROP TABLE IF EXISTS public.configuracao_financeira;` },
];
