/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUfcdsRouteImport } from './routes/_authenticated/ufcds'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNotaHonorariosRouteImport } from './routes/_authenticated/nota-honorarios'
import { Route as AuthenticatedExportarRouteImport } from './routes/_authenticated/exportar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedFormandosIndexRouteImport } from './routes/_authenticated/formandos.index'
import { Route as AuthenticatedFormadoresIndexRouteImport } from './routes/_authenticated/formadores.index'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro.index'
import { Route as AuthenticatedCursosIndexRouteImport } from './routes/_authenticated/cursos.index'
import { Route as AuthenticatedFormandosIdRouteImport } from './routes/_authenticated/formandos.$id'
import { Route as AuthenticatedFormadoresIdRouteImport } from './routes/_authenticated/formadores.$id'
import { Route as AuthenticatedFinanceiroUtilizadoresRouteImport } from './routes/_authenticated/financeiro.utilizadores'
import { Route as AuthenticatedFinanceiroSubsidiosRouteImport } from './routes/_authenticated/financeiro.subsidios'
import { Route as AuthenticatedFinanceiroRubricasRouteImport } from './routes/_authenticated/financeiro.rubricas'
import { Route as AuthenticatedFinanceiroRegrasRouteImport } from './routes/_authenticated/financeiro.regras'
import { Route as AuthenticatedFinanceiroQuilometrosRouteImport } from './routes/_authenticated/financeiro.quilometros'
import { Route as AuthenticatedFinanceiroProcessamentosRouteImport } from './routes/_authenticated/financeiro.processamentos'
import { Route as AuthenticatedFinanceiroHonorariosRouteImport } from './routes/_authenticated/financeiro.honorarios'
import { Route as AuthenticatedFinanceiroConfiguracaoRouteImport } from './routes/_authenticated/financeiro.configuracao'
import { Route as AuthenticatedFinanceiroBolsasRouteImport } from './routes/_authenticated/financeiro.bolsas'
import { Route as AuthenticatedFinanceiroAuditoriaRouteImport } from './routes/_authenticated/financeiro.auditoria'
import { Route as AuthenticatedFinanceiroAlertasRouteImport } from './routes/_authenticated/financeiro.alertas'
import { Route as AuthenticatedCursosIdRouteImport } from './routes/_authenticated/cursos.$id'
import { Route as AuthenticatedCursosIdImportarRouteImport } from './routes/_authenticated/cursos_.$id.importar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUfcdsRoute = AuthenticatedUfcdsRouteImport.update({
  id: '/ufcds',
  path: '/ufcds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotaHonorariosRoute =
  AuthenticatedNotaHonorariosRouteImport.update({
    id: '/nota-honorarios',
    path: '/nota-honorarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExportarRoute = AuthenticatedExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormandosIndexRoute =
  AuthenticatedFormandosIndexRouteImport.update({
    id: '/formandos/',
    path: '/formandos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormadoresIndexRoute =
  AuthenticatedFormadoresIndexRouteImport.update({
    id: '/formadores/',
    path: '/formadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/financeiro/',
    path: '/financeiro/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCursosIndexRoute =
  AuthenticatedCursosIndexRouteImport.update({
    id: '/cursos/',
    path: '/cursos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormandosIdRoute =
  AuthenticatedFormandosIdRouteImport.update({
    id: '/formandos/$id',
    path: '/formandos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormadoresIdRoute =
  AuthenticatedFormadoresIdRouteImport.update({
    id: '/formadores/$id',
    path: '/formadores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroUtilizadoresRoute =
  AuthenticatedFinanceiroUtilizadoresRouteImport.update({
    id: '/financeiro/utilizadores',
    path: '/financeiro/utilizadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroSubsidiosRoute =
  AuthenticatedFinanceiroSubsidiosRouteImport.update({
    id: '/financeiro/subsidios',
    path: '/financeiro/subsidios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRubricasRoute =
  AuthenticatedFinanceiroRubricasRouteImport.update({
    id: '/financeiro/rubricas',
    path: '/financeiro/rubricas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRegrasRoute =
  AuthenticatedFinanceiroRegrasRouteImport.update({
    id: '/financeiro/regras',
    path: '/financeiro/regras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroQuilometrosRoute =
  AuthenticatedFinanceiroQuilometrosRouteImport.update({
    id: '/financeiro/quilometros',
    path: '/financeiro/quilometros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroProcessamentosRoute =
  AuthenticatedFinanceiroProcessamentosRouteImport.update({
    id: '/financeiro/processamentos',
    path: '/financeiro/processamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroHonorariosRoute =
  AuthenticatedFinanceiroHonorariosRouteImport.update({
    id: '/financeiro/honorarios',
    path: '/financeiro/honorarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroConfiguracaoRoute =
  AuthenticatedFinanceiroConfiguracaoRouteImport.update({
    id: '/financeiro/configuracao',
    path: '/financeiro/configuracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroBolsasRoute =
  AuthenticatedFinanceiroBolsasRouteImport.update({
    id: '/financeiro/bolsas',
    path: '/financeiro/bolsas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroAuditoriaRoute =
  AuthenticatedFinanceiroAuditoriaRouteImport.update({
    id: '/financeiro/auditoria',
    path: '/financeiro/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroAlertasRoute =
  AuthenticatedFinanceiroAlertasRouteImport.update({
    id: '/financeiro/alertas',
    path: '/financeiro/alertas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCursosIdRoute = AuthenticatedCursosIdRouteImport.update({
  id: '/cursos/$id',
  path: '/cursos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursosIdImportarRoute =
  AuthenticatedCursosIdImportarRouteImport.update({
    id: '/cursos_/$id/importar',
    path: '/cursos/$id/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exportar': typeof AuthenticatedExportarRoute
  '/nota-honorarios': typeof AuthenticatedNotaHonorariosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/ufcds': typeof AuthenticatedUfcdsRoute
  '/cursos/$id': typeof AuthenticatedCursosIdRoute
  '/financeiro/alertas': typeof AuthenticatedFinanceiroAlertasRoute
  '/financeiro/auditoria': typeof AuthenticatedFinanceiroAuditoriaRoute
  '/financeiro/bolsas': typeof AuthenticatedFinanceiroBolsasRoute
  '/financeiro/configuracao': typeof AuthenticatedFinanceiroConfiguracaoRoute
  '/financeiro/honorarios': typeof AuthenticatedFinanceiroHonorariosRoute
  '/financeiro/processamentos': typeof AuthenticatedFinanceiroProcessamentosRoute
  '/financeiro/quilometros': typeof AuthenticatedFinanceiroQuilometrosRoute
  '/financeiro/regras': typeof AuthenticatedFinanceiroRegrasRoute
  '/financeiro/rubricas': typeof AuthenticatedFinanceiroRubricasRoute
  '/financeiro/subsidios': typeof AuthenticatedFinanceiroSubsidiosRoute
  '/financeiro/utilizadores': typeof AuthenticatedFinanceiroUtilizadoresRoute
  '/formadores/$id': typeof AuthenticatedFormadoresIdRoute
  '/formandos/$id': typeof AuthenticatedFormandosIdRoute
  '/cursos/': typeof AuthenticatedCursosIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/formadores/': typeof AuthenticatedFormadoresIndexRoute
  '/formandos/': typeof AuthenticatedFormandosIndexRoute
  '/cursos/$id/importar': typeof AuthenticatedCursosIdImportarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exportar': typeof AuthenticatedExportarRoute
  '/nota-honorarios': typeof AuthenticatedNotaHonorariosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/ufcds': typeof AuthenticatedUfcdsRoute
  '/cursos/$id': typeof AuthenticatedCursosIdRoute
  '/financeiro/alertas': typeof AuthenticatedFinanceiroAlertasRoute
  '/financeiro/auditoria': typeof AuthenticatedFinanceiroAuditoriaRoute
  '/financeiro/bolsas': typeof AuthenticatedFinanceiroBolsasRoute
  '/financeiro/configuracao': typeof AuthenticatedFinanceiroConfiguracaoRoute
  '/financeiro/honorarios': typeof AuthenticatedFinanceiroHonorariosRoute
  '/financeiro/processamentos': typeof AuthenticatedFinanceiroProcessamentosRoute
  '/financeiro/quilometros': typeof AuthenticatedFinanceiroQuilometrosRoute
  '/financeiro/regras': typeof AuthenticatedFinanceiroRegrasRoute
  '/financeiro/rubricas': typeof AuthenticatedFinanceiroRubricasRoute
  '/financeiro/subsidios': typeof AuthenticatedFinanceiroSubsidiosRoute
  '/financeiro/utilizadores': typeof AuthenticatedFinanceiroUtilizadoresRoute
  '/formadores/$id': typeof AuthenticatedFormadoresIdRoute
  '/formandos/$id': typeof AuthenticatedFormandosIdRoute
  '/cursos': typeof AuthenticatedCursosIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/formadores': typeof AuthenticatedFormadoresIndexRoute
  '/formandos': typeof AuthenticatedFormandosIndexRoute
  '/cursos/$id/importar': typeof AuthenticatedCursosIdImportarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exportar': typeof AuthenticatedExportarRoute
  '/_authenticated/nota-honorarios': typeof AuthenticatedNotaHonorariosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/ufcds': typeof AuthenticatedUfcdsRoute
  '/_authenticated/cursos/$id': typeof AuthenticatedCursosIdRoute
  '/_authenticated/financeiro/alertas': typeof AuthenticatedFinanceiroAlertasRoute
  '/_authenticated/financeiro/auditoria': typeof AuthenticatedFinanceiroAuditoriaRoute
  '/_authenticated/financeiro/bolsas': typeof AuthenticatedFinanceiroBolsasRoute
  '/_authenticated/financeiro/configuracao': typeof AuthenticatedFinanceiroConfiguracaoRoute
  '/_authenticated/financeiro/honorarios': typeof AuthenticatedFinanceiroHonorariosRoute
  '/_authenticated/financeiro/processamentos': typeof AuthenticatedFinanceiroProcessamentosRoute
  '/_authenticated/financeiro/quilometros': typeof AuthenticatedFinanceiroQuilometrosRoute
  '/_authenticated/financeiro/regras': typeof AuthenticatedFinanceiroRegrasRoute
  '/_authenticated/financeiro/rubricas': typeof AuthenticatedFinanceiroRubricasRoute
  '/_authenticated/financeiro/subsidios': typeof AuthenticatedFinanceiroSubsidiosRoute
  '/_authenticated/financeiro/utilizadores': typeof AuthenticatedFinanceiroUtilizadoresRoute
  '/_authenticated/formadores/$id': typeof AuthenticatedFormadoresIdRoute
  '/_authenticated/formandos/$id': typeof AuthenticatedFormandosIdRoute
  '/_authenticated/cursos/': typeof AuthenticatedCursosIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/formadores/': typeof AuthenticatedFormadoresIndexRoute
  '/_authenticated/formandos/': typeof AuthenticatedFormandosIndexRoute
  '/_authenticated/cursos_/$id/importar': typeof AuthenticatedCursosIdImportarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cronograma'
    | '/dashboard'
    | '/exportar'
    | '/nota-honorarios'
    | '/perfil'
    | '/relatorios'
    | '/ufcds'
    | '/cursos/$id'
    | '/financeiro/alertas'
    | '/financeiro/auditoria'
    | '/financeiro/bolsas'
    | '/financeiro/configuracao'
    | '/financeiro/honorarios'
    | '/financeiro/processamentos'
    | '/financeiro/quilometros'
    | '/financeiro/regras'
    | '/financeiro/rubricas'
    | '/financeiro/subsidios'
    | '/financeiro/utilizadores'
    | '/formadores/$id'
    | '/formandos/$id'
    | '/cursos/'
    | '/financeiro/'
    | '/formadores/'
    | '/formandos/'
    | '/cursos/$id/importar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cronograma'
    | '/dashboard'
    | '/exportar'
    | '/nota-honorarios'
    | '/perfil'
    | '/relatorios'
    | '/ufcds'
    | '/cursos/$id'
    | '/financeiro/alertas'
    | '/financeiro/auditoria'
    | '/financeiro/bolsas'
    | '/financeiro/configuracao'
    | '/financeiro/honorarios'
    | '/financeiro/processamentos'
    | '/financeiro/quilometros'
    | '/financeiro/regras'
    | '/financeiro/rubricas'
    | '/financeiro/subsidios'
    | '/financeiro/utilizadores'
    | '/formadores/$id'
    | '/formandos/$id'
    | '/cursos'
    | '/financeiro'
    | '/formadores'
    | '/formandos'
    | '/cursos/$id/importar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cronograma'
    | '/_authenticated/dashboard'
    | '/_authenticated/exportar'
    | '/_authenticated/nota-honorarios'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorios'
    | '/_authenticated/ufcds'
    | '/_authenticated/cursos/$id'
    | '/_authenticated/financeiro/alertas'
    | '/_authenticated/financeiro/auditoria'
    | '/_authenticated/financeiro/bolsas'
    | '/_authenticated/financeiro/configuracao'
    | '/_authenticated/financeiro/honorarios'
    | '/_authenticated/financeiro/processamentos'
    | '/_authenticated/financeiro/quilometros'
    | '/_authenticated/financeiro/regras'
    | '/_authenticated/financeiro/rubricas'
    | '/_authenticated/financeiro/subsidios'
    | '/_authenticated/financeiro/utilizadores'
    | '/_authenticated/formadores/$id'
    | '/_authenticated/formandos/$id'
    | '/_authenticated/cursos/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/formadores/'
    | '/_authenticated/formandos/'
    | '/_authenticated/cursos_/$id/importar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ufcds': {
      id: '/_authenticated/ufcds'
      path: '/ufcds'
      fullPath: '/ufcds'
      preLoaderRoute: typeof AuthenticatedUfcdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nota-honorarios': {
      id: '/_authenticated/nota-honorarios'
      path: '/nota-honorarios'
      fullPath: '/nota-honorarios'
      preLoaderRoute: typeof AuthenticatedNotaHonorariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exportar': {
      id: '/_authenticated/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof AuthenticatedExportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formandos/': {
      id: '/_authenticated/formandos/'
      path: '/formandos'
      fullPath: '/formandos/'
      preLoaderRoute: typeof AuthenticatedFormandosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formadores/': {
      id: '/_authenticated/formadores/'
      path: '/formadores'
      fullPath: '/formadores/'
      preLoaderRoute: typeof AuthenticatedFormadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cursos/': {
      id: '/_authenticated/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof AuthenticatedCursosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formandos/$id': {
      id: '/_authenticated/formandos/$id'
      path: '/formandos/$id'
      fullPath: '/formandos/$id'
      preLoaderRoute: typeof AuthenticatedFormandosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formadores/$id': {
      id: '/_authenticated/formadores/$id'
      path: '/formadores/$id'
      fullPath: '/formadores/$id'
      preLoaderRoute: typeof AuthenticatedFormadoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/utilizadores': {
      id: '/_authenticated/financeiro/utilizadores'
      path: '/financeiro/utilizadores'
      fullPath: '/financeiro/utilizadores'
      preLoaderRoute: typeof AuthenticatedFinanceiroUtilizadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/subsidios': {
      id: '/_authenticated/financeiro/subsidios'
      path: '/financeiro/subsidios'
      fullPath: '/financeiro/subsidios'
      preLoaderRoute: typeof AuthenticatedFinanceiroSubsidiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/rubricas': {
      id: '/_authenticated/financeiro/rubricas'
      path: '/financeiro/rubricas'
      fullPath: '/financeiro/rubricas'
      preLoaderRoute: typeof AuthenticatedFinanceiroRubricasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/regras': {
      id: '/_authenticated/financeiro/regras'
      path: '/financeiro/regras'
      fullPath: '/financeiro/regras'
      preLoaderRoute: typeof AuthenticatedFinanceiroRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/quilometros': {
      id: '/_authenticated/financeiro/quilometros'
      path: '/financeiro/quilometros'
      fullPath: '/financeiro/quilometros'
      preLoaderRoute: typeof AuthenticatedFinanceiroQuilometrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/processamentos': {
      id: '/_authenticated/financeiro/processamentos'
      path: '/financeiro/processamentos'
      fullPath: '/financeiro/processamentos'
      preLoaderRoute: typeof AuthenticatedFinanceiroProcessamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/honorarios': {
      id: '/_authenticated/financeiro/honorarios'
      path: '/financeiro/honorarios'
      fullPath: '/financeiro/honorarios'
      preLoaderRoute: typeof AuthenticatedFinanceiroHonorariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/configuracao': {
      id: '/_authenticated/financeiro/configuracao'
      path: '/financeiro/configuracao'
      fullPath: '/financeiro/configuracao'
      preLoaderRoute: typeof AuthenticatedFinanceiroConfiguracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/bolsas': {
      id: '/_authenticated/financeiro/bolsas'
      path: '/financeiro/bolsas'
      fullPath: '/financeiro/bolsas'
      preLoaderRoute: typeof AuthenticatedFinanceiroBolsasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/auditoria': {
      id: '/_authenticated/financeiro/auditoria'
      path: '/financeiro/auditoria'
      fullPath: '/financeiro/auditoria'
      preLoaderRoute: typeof AuthenticatedFinanceiroAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/alertas': {
      id: '/_authenticated/financeiro/alertas'
      path: '/financeiro/alertas'
      fullPath: '/financeiro/alertas'
      preLoaderRoute: typeof AuthenticatedFinanceiroAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cursos/$id': {
      id: '/_authenticated/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/cursos/$id'
      preLoaderRoute: typeof AuthenticatedCursosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cursos_/$id/importar': {
      id: '/_authenticated/cursos_/$id/importar'
      path: '/cursos/$id/importar'
      fullPath: '/cursos/$id/importar'
      preLoaderRoute: typeof AuthenticatedCursosIdImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportarRoute: typeof AuthenticatedExportarRoute
  AuthenticatedNotaHonorariosRoute: typeof AuthenticatedNotaHonorariosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUfcdsRoute: typeof AuthenticatedUfcdsRoute
  AuthenticatedCursosIdRoute: typeof AuthenticatedCursosIdRoute
  AuthenticatedFinanceiroAlertasRoute: typeof AuthenticatedFinanceiroAlertasRoute
  AuthenticatedFinanceiroAuditoriaRoute: typeof AuthenticatedFinanceiroAuditoriaRoute
  AuthenticatedFinanceiroBolsasRoute: typeof AuthenticatedFinanceiroBolsasRoute
  AuthenticatedFinanceiroConfiguracaoRoute: typeof AuthenticatedFinanceiroConfiguracaoRoute
  AuthenticatedFinanceiroHonorariosRoute: typeof AuthenticatedFinanceiroHonorariosRoute
  AuthenticatedFinanceiroProcessamentosRoute: typeof AuthenticatedFinanceiroProcessamentosRoute
  AuthenticatedFinanceiroQuilometrosRoute: typeof AuthenticatedFinanceiroQuilometrosRoute
  AuthenticatedFinanceiroRegrasRoute: typeof AuthenticatedFinanceiroRegrasRoute
  AuthenticatedFinanceiroRubricasRoute: typeof AuthenticatedFinanceiroRubricasRoute
  AuthenticatedFinanceiroSubsidiosRoute: typeof AuthenticatedFinanceiroSubsidiosRoute
  AuthenticatedFinanceiroUtilizadoresRoute: typeof AuthenticatedFinanceiroUtilizadoresRoute
  AuthenticatedFormadoresIdRoute: typeof AuthenticatedFormadoresIdRoute
  AuthenticatedFormandosIdRoute: typeof AuthenticatedFormandosIdRoute
  AuthenticatedCursosIndexRoute: typeof AuthenticatedCursosIndexRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
  AuthenticatedFormadoresIndexRoute: typeof AuthenticatedFormadoresIndexRoute
  AuthenticatedFormandosIndexRoute: typeof AuthenticatedFormandosIndexRoute
  AuthenticatedCursosIdImportarRoute: typeof AuthenticatedCursosIdImportarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportarRoute: AuthenticatedExportarRoute,
  AuthenticatedNotaHonorariosRoute: AuthenticatedNotaHonorariosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUfcdsRoute: AuthenticatedUfcdsRoute,
  AuthenticatedCursosIdRoute: AuthenticatedCursosIdRoute,
  AuthenticatedFinanceiroAlertasRoute: AuthenticatedFinanceiroAlertasRoute,
  AuthenticatedFinanceiroAuditoriaRoute: AuthenticatedFinanceiroAuditoriaRoute,
  AuthenticatedFinanceiroBolsasRoute: AuthenticatedFinanceiroBolsasRoute,
  AuthenticatedFinanceiroConfiguracaoRoute:
    AuthenticatedFinanceiroConfiguracaoRoute,
  AuthenticatedFinanceiroHonorariosRoute:
    AuthenticatedFinanceiroHonorariosRoute,
  AuthenticatedFinanceiroProcessamentosRoute:
    AuthenticatedFinanceiroProcessamentosRoute,
  AuthenticatedFinanceiroQuilometrosRoute:
    AuthenticatedFinanceiroQuilometrosRoute,
  AuthenticatedFinanceiroRegrasRoute: AuthenticatedFinanceiroRegrasRoute,
  AuthenticatedFinanceiroRubricasRoute: AuthenticatedFinanceiroRubricasRoute,
  AuthenticatedFinanceiroSubsidiosRoute: AuthenticatedFinanceiroSubsidiosRoute,
  AuthenticatedFinanceiroUtilizadoresRoute:
    AuthenticatedFinanceiroUtilizadoresRoute,
  AuthenticatedFormadoresIdRoute: AuthenticatedFormadoresIdRoute,
  AuthenticatedFormandosIdRoute: AuthenticatedFormandosIdRoute,
  AuthenticatedCursosIndexRoute: AuthenticatedCursosIndexRoute,
  AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  AuthenticatedFormadoresIndexRoute: AuthenticatedFormadoresIndexRoute,
  AuthenticatedFormandosIndexRoute: AuthenticatedFormandosIndexRoute,
  AuthenticatedCursosIdImportarRoute: AuthenticatedCursosIdImportarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
