/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentacaoRouteImport } from './routes/_authenticated/documentacao'
import { Route as AuthenticatedExportarRouteImport } from './routes/_authenticated/exportar'
import { Route as AuthenticatedNotaHonorariosRouteImport } from './routes/_authenticated/nota-honorarios'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedUfcdsRouteImport } from './routes/_authenticated/ufcds'
import { Route as AuthenticatedContratosFormadorRouteImport } from './routes/_authenticated/contratos.formador'
import { Route as AuthenticatedContratosFormandoRouteImport } from './routes/_authenticated/contratos.formando'
import { Route as AuthenticatedContratosHistoricoRouteImport } from './routes/_authenticated/contratos.historico'
import { Route as AuthenticatedCursosIndexRouteImport } from './routes/_authenticated/cursos.index'
import { Route as AuthenticatedCursosIdRouteImport } from './routes/_authenticated/cursos.$id'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro.index'
import { Route as AuthenticatedFinanceiroConfiguracaoRouteImport } from './routes/_authenticated/financeiro.configuracao'
import { Route as AuthenticatedFinanceiroDespesasRouteImport } from './routes/_authenticated/financeiro.despesas'
import { Route as AuthenticatedFormadoresIndexRouteImport } from './routes/_authenticated/formadores.index'
import { Route as AuthenticatedFormadoresIdRouteImport } from './routes/_authenticated/formadores.$id'
import { Route as AuthenticatedFormandosIndexRouteImport } from './routes/_authenticated/formandos.index'
import { Route as AuthenticatedFormandosIdRouteImport } from './routes/_authenticated/formandos.$id'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated/projetos.index'
import { Route as AuthenticatedProjetosIdRouteImport } from './routes/_authenticated/projetos.$id'
import { Route as AuthenticatedFinanceiroFormadoresIndexRouteImport } from './routes/_authenticated/financeiro.formadores.index'
import { Route as AuthenticatedFinanceiroFormadoresIdRouteImport } from './routes/_authenticated/financeiro.formadores.$id'
import { Route as AuthenticatedFinanceiroProcessamentosIndexRouteImport } from './routes/_authenticated/financeiro.processamentos.index'
import { Route as AuthenticatedFinanceiroProcessamentosIdRouteImport } from './routes/_authenticated/financeiro.processamentos.$id'
import { Route as AuthenticatedFinanceiroProcessamentosNovoRouteImport } from './routes/_authenticated/financeiro.processamentos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentacaoRoute =
  AuthenticatedDocumentacaoRouteImport.update({
    id: '/documentacao',
    path: '/documentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExportarRoute = AuthenticatedExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotaHonorariosRoute =
  AuthenticatedNotaHonorariosRouteImport.update({
    id: '/nota-honorarios',
    path: '/nota-honorarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUfcdsRoute = AuthenticatedUfcdsRouteImport.update({
  id: '/ufcds',
  path: '/ufcds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosFormadorRoute =
  AuthenticatedContratosFormadorRouteImport.update({
    id: '/contratos/formador',
    path: '/contratos/formador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosFormandoRoute =
  AuthenticatedContratosFormandoRouteImport.update({
    id: '/contratos/formando',
    path: '/contratos/formando',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosHistoricoRoute =
  AuthenticatedContratosHistoricoRouteImport.update({
    id: '/contratos/historico',
    path: '/contratos/historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCursosIndexRoute =
  AuthenticatedCursosIndexRouteImport.update({
    id: '/cursos/',
    path: '/cursos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCursosIdRoute = AuthenticatedCursosIdRouteImport.update({
  id: '/cursos/$id',
  path: '/cursos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/financeiro/',
    path: '/financeiro/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroConfiguracaoRoute =
  AuthenticatedFinanceiroConfiguracaoRouteImport.update({
    id: '/financeiro/configuracao',
    path: '/financeiro/configuracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroDespesasRoute =
  AuthenticatedFinanceiroDespesasRouteImport.update({
    id: '/financeiro/despesas',
    path: '/financeiro/despesas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormadoresIndexRoute =
  AuthenticatedFormadoresIndexRouteImport.update({
    id: '/formadores/',
    path: '/formadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormadoresIdRoute =
  AuthenticatedFormadoresIdRouteImport.update({
    id: '/formadores/$id',
    path: '/formadores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormandosIndexRoute =
  AuthenticatedFormandosIndexRouteImport.update({
    id: '/formandos/',
    path: '/formandos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFormandosIdRoute =
  AuthenticatedFormandosIdRouteImport.update({
    id: '/formandos/$id',
    path: '/formandos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/projetos/',
    path: '/projetos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjetosIdRoute = AuthenticatedProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroFormadoresIndexRoute =
  AuthenticatedFinanceiroFormadoresIndexRouteImport.update({
    id: '/financeiro/formadores/',
    path: '/financeiro/formadores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroFormadoresIdRoute =
  AuthenticatedFinanceiroFormadoresIdRouteImport.update({
    id: '/financeiro/formadores/$id',
    path: '/financeiro/formadores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroProcessamentosIndexRoute =
  AuthenticatedFinanceiroProcessamentosIndexRouteImport.update({
    id: '/financeiro/processamentos/',
    path: '/financeiro/processamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroProcessamentosIdRoute =
  AuthenticatedFinanceiroProcessamentosIdRouteImport.update({
    id: '/financeiro/processamentos/$id',
    path: '/financeiro/processamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroProcessamentosNovoRoute =
  AuthenticatedFinanceiroProcessamentosNovoRouteImport.update({
    id: '/financeiro/processamentos/novo',
    path: '/financeiro/processamentos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentacao': typeof AuthenticatedDocumentacaoRoute
  '/exportar': typeof AuthenticatedExportarRoute
  '/nota-honorarios': typeof AuthenticatedNotaHonorariosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/ufcds': typeof AuthenticatedUfcdsRoute
  '/contratos/formador': typeof AuthenticatedContratosFormadorRoute
  '/contratos/formando': typeof AuthenticatedContratosFormandoRoute
  '/contratos/historico': typeof AuthenticatedContratosHistoricoRoute
  '/cursos/$id': typeof AuthenticatedCursosIdRoute
  '/financeiro/configuracao': typeof AuthenticatedFinanceiroConfiguracaoRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/formadores/$id': typeof AuthenticatedFormadoresIdRoute
  '/formandos/$id': typeof AuthenticatedFormandosIdRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/cursos/': typeof AuthenticatedCursosIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/formadores/': typeof AuthenticatedFormadoresIndexRoute
  '/formandos/': typeof AuthenticatedFormandosIndexRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/financeiro/formadores/$id': typeof AuthenticatedFinanceiroFormadoresIdRoute
  '/financeiro/processamentos/$id': typeof AuthenticatedFinanceiroProcessamentosIdRoute
  '/financeiro/processamentos/novo': typeof AuthenticatedFinanceiroProcessamentosNovoRoute
  '/financeiro/formadores/': typeof AuthenticatedFinanceiroFormadoresIndexRoute
  '/financeiro/processamentos/': typeof AuthenticatedFinanceiroProcessamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentacao': typeof AuthenticatedDocumentacaoRoute
  '/exportar': typeof AuthenticatedExportarRoute
  '/nota-honorarios': typeof AuthenticatedNotaHonorariosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/ufcds': typeof AuthenticatedUfcdsRoute
  '/contratos/formador': typeof AuthenticatedContratosFormadorRoute
  '/contratos/formando': typeof AuthenticatedContratosFormandoRoute
  '/contratos/historico': typeof AuthenticatedContratosHistoricoRoute
  '/cursos/$id': typeof AuthenticatedCursosIdRoute
  '/financeiro/configuracao': typeof AuthenticatedFinanceiroConfiguracaoRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/formadores/$id': typeof AuthenticatedFormadoresIdRoute
  '/formandos/$id': typeof AuthenticatedFormandosIdRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/cursos': typeof AuthenticatedCursosIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/formadores': typeof AuthenticatedFormadoresIndexRoute
  '/formandos': typeof AuthenticatedFormandosIndexRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
  '/financeiro/formadores/$id': typeof AuthenticatedFinanceiroFormadoresIdRoute
  '/financeiro/processamentos/$id': typeof AuthenticatedFinanceiroProcessamentosIdRoute
  '/financeiro/processamentos/novo': typeof AuthenticatedFinanceiroProcessamentosNovoRoute
  '/financeiro/formadores': typeof AuthenticatedFinanceiroFormadoresIndexRoute
  '/financeiro/processamentos': typeof AuthenticatedFinanceiroProcessamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentacao': typeof AuthenticatedDocumentacaoRoute
  '/_authenticated/exportar': typeof AuthenticatedExportarRoute
  '/_authenticated/nota-honorarios': typeof AuthenticatedNotaHonorariosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/ufcds': typeof AuthenticatedUfcdsRoute
  '/_authenticated/contratos/formador': typeof AuthenticatedContratosFormadorRoute
  '/_authenticated/contratos/formando': typeof AuthenticatedContratosFormandoRoute
  '/_authenticated/contratos/historico': typeof AuthenticatedContratosHistoricoRoute
  '/_authenticated/cursos/$id': typeof AuthenticatedCursosIdRoute
  '/_authenticated/financeiro/configuracao': typeof AuthenticatedFinanceiroConfiguracaoRoute
  '/_authenticated/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/_authenticated/formadores/$id': typeof AuthenticatedFormadoresIdRoute
  '/_authenticated/formandos/$id': typeof AuthenticatedFormandosIdRoute
  '/_authenticated/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/_authenticated/cursos/': typeof AuthenticatedCursosIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/formadores/': typeof AuthenticatedFormadoresIndexRoute
  '/_authenticated/formandos/': typeof AuthenticatedFormandosIndexRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/_authenticated/financeiro/formadores/$id': typeof AuthenticatedFinanceiroFormadoresIdRoute
  '/_authenticated/financeiro/processamentos/$id': typeof AuthenticatedFinanceiroProcessamentosIdRoute
  '/_authenticated/financeiro/processamentos/novo': typeof AuthenticatedFinanceiroProcessamentosNovoRoute
  '/_authenticated/financeiro/formadores/': typeof AuthenticatedFinanceiroFormadoresIndexRoute
  '/_authenticated/financeiro/processamentos/': typeof AuthenticatedFinanceiroProcessamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cronograma'
    | '/dashboard'
    | '/documentacao'
    | '/exportar'
    | '/nota-honorarios'
    | '/perfil'
    | '/relatorios'
    | '/ufcds'
    | '/contratos/formador'
    | '/contratos/formando'
    | '/contratos/historico'
    | '/cursos/$id'
    | '/financeiro/configuracao'
    | '/financeiro/despesas'
    | '/formadores/$id'
    | '/formandos/$id'
    | '/projetos/$id'
    | '/cursos/'
    | '/financeiro/'
    | '/formadores/'
    | '/formandos/'
    | '/projetos/'
    | '/financeiro/formadores/$id'
    | '/financeiro/processamentos/$id'
    | '/financeiro/processamentos/novo'
    | '/financeiro/formadores/'
    | '/financeiro/processamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cronograma'
    | '/dashboard'
    | '/documentacao'
    | '/exportar'
    | '/nota-honorarios'
    | '/perfil'
    | '/relatorios'
    | '/ufcds'
    | '/contratos/formador'
    | '/contratos/formando'
    | '/contratos/historico'
    | '/cursos/$id'
    | '/financeiro/configuracao'
    | '/financeiro/despesas'
    | '/formadores/$id'
    | '/formandos/$id'
    | '/projetos/$id'
    | '/cursos'
    | '/financeiro'
    | '/formadores'
    | '/formandos'
    | '/projetos'
    | '/financeiro/formadores/$id'
    | '/financeiro/processamentos/$id'
    | '/financeiro/processamentos/novo'
    | '/financeiro/formadores'
    | '/financeiro/processamentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cronograma'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentacao'
    | '/_authenticated/exportar'
    | '/_authenticated/nota-honorarios'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorios'
    | '/_authenticated/ufcds'
    | '/_authenticated/contratos/formador'
    | '/_authenticated/contratos/formando'
    | '/_authenticated/contratos/historico'
    | '/_authenticated/cursos/$id'
    | '/_authenticated/financeiro/configuracao'
    | '/_authenticated/financeiro/despesas'
    | '/_authenticated/formadores/$id'
    | '/_authenticated/formandos/$id'
    | '/_authenticated/projetos/$id'
    | '/_authenticated/cursos/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/formadores/'
    | '/_authenticated/formandos/'
    | '/_authenticated/projetos/'
    | '/_authenticated/financeiro/formadores/$id'
    | '/_authenticated/financeiro/processamentos/$id'
    | '/_authenticated/financeiro/processamentos/novo'
    | '/_authenticated/financeiro/formadores/'
    | '/_authenticated/financeiro/processamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentacao': {
      id: '/_authenticated/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof AuthenticatedDocumentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exportar': {
      id: '/_authenticated/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof AuthenticatedExportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nota-honorarios': {
      id: '/_authenticated/nota-honorarios'
      path: '/nota-honorarios'
      fullPath: '/nota-honorarios'
      preLoaderRoute: typeof AuthenticatedNotaHonorariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ufcds': {
      id: '/_authenticated/ufcds'
      path: '/ufcds'
      fullPath: '/ufcds'
      preLoaderRoute: typeof AuthenticatedUfcdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/formador': {
      id: '/_authenticated/contratos/formador'
      path: '/contratos/formador'
      fullPath: '/contratos/formador'
      preLoaderRoute: typeof AuthenticatedContratosFormadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/formando': {
      id: '/_authenticated/contratos/formando'
      path: '/contratos/formando'
      fullPath: '/contratos/formando'
      preLoaderRoute: typeof AuthenticatedContratosFormandoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/historico': {
      id: '/_authenticated/contratos/historico'
      path: '/contratos/historico'
      fullPath: '/contratos/historico'
      preLoaderRoute: typeof AuthenticatedContratosHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cursos/': {
      id: '/_authenticated/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof AuthenticatedCursosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cursos/$id': {
      id: '/_authenticated/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/cursos/$id'
      preLoaderRoute: typeof AuthenticatedCursosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/configuracao': {
      id: '/_authenticated/financeiro/configuracao'
      path: '/financeiro/configuracao'
      fullPath: '/financeiro/configuracao'
      preLoaderRoute: typeof AuthenticatedFinanceiroConfiguracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/despesas': {
      id: '/_authenticated/financeiro/despesas'
      path: '/financeiro/despesas'
      fullPath: '/financeiro/despesas'
      preLoaderRoute: typeof AuthenticatedFinanceiroDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formadores/': {
      id: '/_authenticated/formadores/'
      path: '/formadores'
      fullPath: '/formadores/'
      preLoaderRoute: typeof AuthenticatedFormadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formadores/$id': {
      id: '/_authenticated/formadores/$id'
      path: '/formadores/$id'
      fullPath: '/formadores/$id'
      preLoaderRoute: typeof AuthenticatedFormadoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formandos/': {
      id: '/_authenticated/formandos/'
      path: '/formandos'
      fullPath: '/formandos/'
      preLoaderRoute: typeof AuthenticatedFormandosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/formandos/$id': {
      id: '/_authenticated/formandos/$id'
      path: '/formandos/$id'
      fullPath: '/formandos/$id'
      preLoaderRoute: typeof AuthenticatedFormandosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projetos/$id': {
      id: '/_authenticated/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof AuthenticatedProjetosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/formadores/': {
      id: '/_authenticated/financeiro/formadores/'
      path: '/financeiro/formadores'
      fullPath: '/financeiro/formadores/'
      preLoaderRoute: typeof AuthenticatedFinanceiroFormadoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/formadores/$id': {
      id: '/_authenticated/financeiro/formadores/$id'
      path: '/financeiro/formadores/$id'
      fullPath: '/financeiro/formadores/$id'
      preLoaderRoute: typeof AuthenticatedFinanceiroFormadoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/processamentos/': {
      id: '/_authenticated/financeiro/processamentos/'
      path: '/financeiro/processamentos'
      fullPath: '/financeiro/processamentos/'
      preLoaderRoute: typeof AuthenticatedFinanceiroProcessamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/processamentos/$id': {
      id: '/_authenticated/financeiro/processamentos/$id'
      path: '/financeiro/processamentos/$id'
      fullPath: '/financeiro/processamentos/$id'
      preLoaderRoute: typeof AuthenticatedFinanceiroProcessamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/processamentos/novo': {
      id: '/_authenticated/financeiro/processamentos/novo'
      path: '/financeiro/processamentos/novo'
      fullPath: '/financeiro/processamentos/novo'
      preLoaderRoute: typeof AuthenticatedFinanceiroProcessamentosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentacaoRoute: typeof AuthenticatedDocumentacaoRoute
  AuthenticatedExportarRoute: typeof AuthenticatedExportarRoute
  AuthenticatedNotaHonorariosRoute: typeof AuthenticatedNotaHonorariosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUfcdsRoute: typeof AuthenticatedUfcdsRoute
  AuthenticatedContratosFormadorRoute: typeof AuthenticatedContratosFormadorRoute
  AuthenticatedContratosFormandoRoute: typeof AuthenticatedContratosFormandoRoute
  AuthenticatedContratosHistoricoRoute: typeof AuthenticatedContratosHistoricoRoute
  AuthenticatedCursosIdRoute: typeof AuthenticatedCursosIdRoute
  AuthenticatedFinanceiroConfiguracaoRoute: typeof AuthenticatedFinanceiroConfiguracaoRoute
  AuthenticatedFinanceiroDespesasRoute: typeof AuthenticatedFinanceiroDespesasRoute
  AuthenticatedFormadoresIdRoute: typeof AuthenticatedFormadoresIdRoute
  AuthenticatedFormandosIdRoute: typeof AuthenticatedFormandosIdRoute
  AuthenticatedProjetosIdRoute: typeof AuthenticatedProjetosIdRoute
  AuthenticatedCursosIndexRoute: typeof AuthenticatedCursosIndexRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
  AuthenticatedFormadoresIndexRoute: typeof AuthenticatedFormadoresIndexRoute
  AuthenticatedFormandosIndexRoute: typeof AuthenticatedFormandosIndexRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
  AuthenticatedFinanceiroFormadoresIdRoute: typeof AuthenticatedFinanceiroFormadoresIdRoute
  AuthenticatedFinanceiroProcessamentosIdRoute: typeof AuthenticatedFinanceiroProcessamentosIdRoute
  AuthenticatedFinanceiroProcessamentosNovoRoute: typeof AuthenticatedFinanceiroProcessamentosNovoRoute
  AuthenticatedFinanceiroFormadoresIndexRoute: typeof AuthenticatedFinanceiroFormadoresIndexRoute
  AuthenticatedFinanceiroProcessamentosIndexRoute: typeof AuthenticatedFinanceiroProcessamentosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentacaoRoute: AuthenticatedDocumentacaoRoute,
  AuthenticatedExportarRoute: AuthenticatedExportarRoute,
  AuthenticatedNotaHonorariosRoute: AuthenticatedNotaHonorariosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUfcdsRoute: AuthenticatedUfcdsRoute,
  AuthenticatedContratosFormadorRoute: AuthenticatedContratosFormadorRoute,
  AuthenticatedContratosFormandoRoute: AuthenticatedContratosFormandoRoute,
  AuthenticatedContratosHistoricoRoute: AuthenticatedContratosHistoricoRoute,
  AuthenticatedCursosIdRoute: AuthenticatedCursosIdRoute,
  AuthenticatedFinanceiroConfiguracaoRoute:
    AuthenticatedFinanceiroConfiguracaoRoute,
  AuthenticatedFinanceiroDespesasRoute: AuthenticatedFinanceiroDespesasRoute,
  AuthenticatedFormadoresIdRoute: AuthenticatedFormadoresIdRoute,
  AuthenticatedFormandosIdRoute: AuthenticatedFormandosIdRoute,
  AuthenticatedProjetosIdRoute: AuthenticatedProjetosIdRoute,
  AuthenticatedCursosIndexRoute: AuthenticatedCursosIndexRoute,
  AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  AuthenticatedFormadoresIndexRoute: AuthenticatedFormadoresIndexRoute,
  AuthenticatedFormandosIndexRoute: AuthenticatedFormandosIndexRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
  AuthenticatedFinanceiroFormadoresIdRoute:
    AuthenticatedFinanceiroFormadoresIdRoute,
  AuthenticatedFinanceiroProcessamentosIdRoute:
    AuthenticatedFinanceiroProcessamentosIdRoute,
  AuthenticatedFinanceiroProcessamentosNovoRoute:
    AuthenticatedFinanceiroProcessamentosNovoRoute,
  AuthenticatedFinanceiroFormadoresIndexRoute:
    AuthenticatedFinanceiroFormadoresIndexRoute,
  AuthenticatedFinanceiroProcessamentosIndexRoute:
    AuthenticatedFinanceiroProcessamentosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
