// Imports a backup-formacao-*.zip generated by the online app's Exportar page.
// - data.json → tables (full replace)
// - storage/<bucket>/<path...> → docs/<bucket>/<path...> on the pen drive
//
// Returns a per-table count summary so the caller can show a confirmation.

import JSZip from "jszip";
import { createAndFillTable, normalizeImportedSchema } from "./schema";
import { flushNow } from "./sqljs";
import { writeFileAt } from "./persistence";

export type ImportSummary = {
  tables: Record<string, number>;
  files: number;
  warnings: string[];
};

const STORAGE_BUCKET_TO_DOCS: Record<string, string> = {
  "formador-documentos": "docs/formadores",
  "formando-pra": "docs/formandos-pra",
};

export async function importBackupZip(file: File, onProgress?: (msg: string) => void): Promise<ImportSummary> {
  const zip = await JSZip.loadAsync(file);
  const summary: ImportSummary = { tables: {}, files: 0, warnings: [] };

  // ---- 1) data.json -------------------------------------------------
  const dataEntry = zip.file("data.json");
  if (!dataEntry) throw new Error("O .zip não contém data.json");
  onProgress?.("A ler data.json…");
  const text = await dataEntry.async("string");
  const parsed = JSON.parse(text) as { tables: Record<string, Record<string, unknown>[]> };

  for (const [name, rows] of Object.entries(parsed.tables ?? {})) {
    onProgress?.(`A importar tabela ${name} (${rows.length})…`);
    createAndFillTable(name, rows);
    summary.tables[name] = rows.length;
  }

  // ---- 2) storage/** → docs/** ------------------------------------
  const fileEntries: { path: string; entry: JSZip.JSZipObject }[] = [];
  zip.forEach((path, entry) => {
    if (entry.dir) return;
    if (!path.startsWith("storage/")) return;
    fileEntries.push({ path, entry });
  });

  for (let i = 0; i < fileEntries.length; i++) {
    const { path, entry } = fileEntries[i];
    // path = "storage/<bucket>/<rest...>"
    const parts = path.split("/");
    const bucket = parts[1];
    const rest = parts.slice(2).join("/");
    const target = STORAGE_BUCKET_TO_DOCS[bucket] ?? `docs/${bucket}`;
    const destPath = `${target}/${rest}`;
    onProgress?.(`A copiar ficheiro ${i + 1}/${fileEntries.length}: ${rest}`);
    try {
      const blob = await entry.async("blob");
      await writeFileAt(destPath, blob);
      summary.files++;
    } catch (e) {
      summary.warnings.push(`Falha em ${path}: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  onProgress?.("A normalizar schema…");
  normalizeImportedSchema();
  onProgress?.("A gravar database.db…");
  await flushNow();
  return summary;
}
